### ISSUE TITLE
.vim directory not autocreating

### ISSUE THREAD

**Issue by manorit2001** [emersonmx/vim-prj#1]
I was getting a file save error when trying to save after `call prj#edit()`. Apparently, It ran fine after I created a directory `.vim` in the root of the project folder

**Comment by emersonmx** [comment]
Hello 😄 

I guess this bug pass because I have this in my vimrc. 😅 
https://stackoverflow.com/a/4294176

**Comment by manorit2001** [comment]
> Hello 
> 
> I guess this bug pass because I have this in my vimrc. 
> https://stackoverflow.com/a/4294176

Ah, didn't know about it. Thanks!

Though, if this is the case then maybe it would be nice if the default creation is `.vimrc` instead of `.vim/vimrc` as then the plugin won't have any such directory dependencies for it's usage. What do you think?

**Comment by emersonmx** [comment]
I guess using `.vimrc` is ok. I don't remember why I put `.vim/vimrc`. 🤔 

EDIT:
But I believe there will be some conflict with `~/.vimrc`.

**Comment by manorit2001** [comment]
> EDIT:
> But I believe there will be some conflict with `~/.vimrc`.

Oh, I don't know the working of the plugin so can't really comment on that. Had a suggestion so just told. Feel free to close the issue if it isn't possible

**Comment by emersonmx** [comment]
With this issue I ended up finding another one.
It was not possible to use another configuration file name.
So I decided to rename the file to `.prjrc` by default and fix the custom configuration file option.

Thank you for your contribution and I am closing this issue for now.
