### ISSUE TITLE
autocmd commands

### ISSUE THREAD

**Issue by manorit2001** [emersonmx/vim-prj#2]
I was trying to map certain keys to specific functions based on filetype by using `autocmd` command in this. But, it did not seem to work. Do you think it might be related to how this plugin works?

**Comment by emersonmx** [comment]
I don't know. Is it possible to show an example of autocmd that you are trying to do?

**Comment by manorit2001** [comment]
Sure, I was trying to map my linting commands to specific project using this
```
autocmd filetype python nnoremap <F2> :w <bar> exec '!autopep8 --in-place --ignore E402,F401,E501 '.shellescape('%').' && flake8 --ignore E402,F401,E501 '.shellescape('%')<CR>
```
when i removed `autocmd filetype python` the command was `F2` was mapped properly, but with `autocmd` it wasn't being mapped at all

**Comment by emersonmx** [comment]
I ran vim with `vim -u NONE` to start without plugins. The autocmd config doesn't work. So it is not problem of this plugin.

Run `set ft ?` and see if return `filetype=python`. Otherwise, put `filetype plugin indent on` and `syntax on` in you vimrc.
https://vim.fandom.com/wiki/Filetype.vim#Example

I usually put these mapping settings in `~/.config/nvim/after/ftplugin/python.vim` (~/.config/vim/after/ftplugin/python.vim on vim) so I don't have to use autocmd.

**Comment by manorit2001** [comment]
> Run `set ft ?` and see if return `filetype=python`

I am sure the filetype must be python as the other `autocmd filetype python` commands which are in my global `.vimrc` works as intended with `.py` files

> I usually put these mapping settings in `~/.config/nvim/after/ftplugin/python.vim` (~/.config/vim/after/ftplugin/python.vim on vim) so I don't have to use autocmd.

If I do this then I won't be able to use vim-prj to set different key-maps per project :p

**Comment by manorit2001** [comment]
This is the most smallest example I could do in my laptop
1. Create `.prjrc` with this content
```
set nocompatible 
filetype plugin indent on
syntax on

autocmd filetype python nnoremap <F2> :!echo hi<CR>
```
2. `vim -u .prjrc temp.py`, now `F2` should print "hi"
3. run `vim` normally which will ask for authorisation with `.prjrc`. Allow it.  `F2` won't print "hi"

**Comment by emersonmx** [comment]
In nvim it worked normally. 🤔

**Comment by manorit2001** [comment]
> In nvim it worked normally.

What about `vim`. Did it work on your pc with `vim-prj` and this `.prjrc`? 

If it worked, then maybe some other plugin is clashing with the working of `vim-prj`
If not, then maybe `nvim` and `vim` have some differences with the working of plugins

**Comment by emersonmx** [comment]
> What about `vim`. Did it work on your pc with `vim-prj` and this `.prjrc`?

Nowadays my workflows is normally by language and so I don't use much `.prjrc`.

> If it worked, then maybe some other plugin is clashing with the working of `vim-prj`
> If not, then maybe `nvim` and `vim` have some differences with the working of plugins

I ran vim in a docker and it printed "hi" anyway.

**Comment by manorit2001** [comment]
Oh okay, thanks for the info
